[project]
name = "yolo-detection-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.120.0",
    "pillow>=12.0.0",
    "python-multipart>=0.0.20",
    "ultralytics>=8.3.221",
    "uvicorn>=0.38.0",
]
