name: Build and Push to Artifact Registry

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: clearskin-479420
  REGION: us-east1
  GAR_LOCATION: us-east1-docker.pkg.dev/clearskin-479420/clearskin-backend

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Authenticate to google cloud"
        id: "auth"
        uses: "google-github-actions/auth@v3"
        with:
          workload_identity_provider: "${{ secrets.WIF }}"
          service_account: "${{ secrets.SERVICE_ACCOUNT }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ env.GAR_LOCATION }}
        working-directory: backend/

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}
