name: Build and Push to Artifact Registry

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: clearskin-479420
  REGION: us-east1
  GAR_LOCATION: us-east1-docker.pkg.dev/clearskin-479420/clearskin-backend/backend:latest

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker authentication
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        working-directory: backend/
        run: |
          docker build . --file Dockerfile --tag ${{ env.GAR_LOCATION }}

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}

